#!/bin/sh
# NOTE: This script will not produce source code annotated results.
docker run -it -v ${PWD}/results:/results rishiramraj/range_n valgrind --tool=callgrind --callgrind-out-file=/results/callgrind.out python -c 'range(10000000)'
